version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_server_container  
    ports:
      - "8000:8000"
    volumes:
      - serverdata:/serverdata

volumes:
  serverdata:
